### ISSUE TITLE
 where can I obtain the dataset used in the experiment

### ISSUE THREAD

**Issue by CannonWWW** [TsinghuaDatabaseGroup/DB-GPT#1]

**Comment by zhouxh19** [comment]
Here are the dataset locations :) 
1) Query Rewrite: https://github.com/TsinghuaDatabaseGroup/DB-GPT/tree/main/query_rewrite/data
2) Index Tuning: https://github.com/TsinghuaDatabaseGroup/DB-GPT/tree/main/index_tuning/data
