### ISSUE TITLE
[bug] 启动后无法对话

### ISSUE THREAD

**Issue by IamWWT** [TsinghuaDatabaseGroup/DB-GPT#126]
![截图 2024-05-01 16-22-44](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/35350787/0421c761-3e22-4c4a-9277-b05a57ba255f)

## 模型配置
EMBEDDING_MODEL = "bge-m3e"
LLM_MODELS = ["chatglm3-6b"] 
MODEL_PATH = {
    "embed_model": { 
        "bge-m3e": "/home/wwt/repo/aigc/models/embedding/BAAI_bge-m3", # Download path of embedding model. 
    },

    "llm_model": { 
        "chatglm3-6b": "/home/wwt/repo/aigc/models/glm/THUDM_chatglm3-6b"
    },
}
## 初始化知识库和配置文件
docker start mysql
docker start postgre12
python copy_config_example.py

## 前端安装
cd webui
pnpm install

## 启动
python startup.py -a  # 模型也看加载了，但是报如图错误，也无法对话，这是为啥呀。

![截图 2024-05-01 16-29-22](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/35350787/b1519111-346a-4003-995e-d25b6e5fc800)

**Comment by HungryFour** [comment]
您好，请检查 `configs/server_config.py ` 第16行的设置。需要将前端访问的api按照实际情况更改一下。

**Comment by IamWWT** [comment]
> 您好，请检查 `configs/server_config.py ` 第16行的设置。需要将前端访问的api按照实际情况更改一下。

感谢，已经配置好。同时，我发现了一个知识库初始化过程的es的使用问题。已经修改代码部分解决，这里给出我的代码修改参考如下图。

![截图 2024-05-02 11-43-36](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/35350787/7708780f-bd2e-4d6a-a4d6-6d910ababd38)


![截图 2024-05-02 14-53-53](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/35350787/6fb0eca0-3dfb-46f0-bcdb-5a5817d4395a)
