### ISSUE TITLE
Invalid file path involved for Win10

### ISSUE THREAD

**Issue by Beliefuture** [TsinghuaDatabaseGroup/DB-GPT#22]
The path of file is not allowed to contain the following characters in Win10, which makes the `clone` command failed.

```
\ / : * ? " < > |
```

i.e., `knowledge_json/knowledge_from_document/raw`

<img width="306" alt="3af942e4d6c50380c1e899949d87137" src="https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/62245023/3fe668c7-e345-4929-bb03-e740a83b60ca">

**Comment by zhouxh19** [comment]
Thanks for your kind feedback! We have reviewed all the files and the updates are as follows:

./knowledge_json/knowledge_from_document/raw/5.6.6_Temporary_Table_Transformation:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.6.6_Temporary_Table_Transformation_Scenario.txt

./knowledge_json/knowledge_from_document/raw/5.10.4_Factorization_of_Outer_Joins:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.10.4_Factorization_of_Outer_Joins_Scenario.txt

./knowledge_json/knowledge_from_document/raw/5.8.3_Cursor-Duration_Temporary_Tables:_Example.txt -> ./knowledge_json/knowledge_from_document/raw/5.8.3_Cursor-Duration_Temporary_Tables_Example.txt

./knowledge_json/knowledge_from_document/raw/5.9.4_Table_Expansion_and_Star_Transformation:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.9.4_Table_Expansion_and_Star_Transformation_Scenario.txt

./knowledge_json/knowledge_from_document/raw/5.9.3_Table_Expansion:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.9.3_Table_Expansion_Scenario.txt

./knowledge_json/knowledge_from_document/raw/5.10.3_Factorization_and_Join_Orders:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.10.3_Factorization_and_Join_Orders_Scenario.txt

./knowledge_json/knowledge_from_document/raw/5.6.5_Star_Transformation:_Scenario.txt -> ./knowledge_json/knowledge_from_document/raw/5.6.5_Star_Transformation_Scenario.txt
