### ISSUE TITLE
sh run_demo.sh  error

### ISSUE THREAD

**Issue by yyghefei** [TsinghuaDatabaseGroup/DB-GPT#27]
SQL Execution Fatal!!
ERROR:root:obtain_historical_queries_statistics Fails!

**Comment by zhouxh19** [comment]
Thank you for your feedback. Try to solve it in two ways:
1. Check the "POSTGRESQL" settings in ./config/tool_config.yaml. Make sure you can access the target database.
2. Check the pg_stat_statements extension in your POSTGRESQL database. You can execute "select * from pg_stat_statements limit 1" on the target database. If the sql fails, you need to enable the view (https://pganalyze.com/docs/install/01_enabling_pg_stat_statements) ahead of time.

**Comment by zhouxh19** [comment]
Note if you want to easily set up the demo, modify two lines in the multiagents/tools/metrics.py script:
workload_statistics = db.obtain_historical_queries_statistics() --> workload_statistics = []
slow_queries = obtain_slow_queries(database_server_conf) --> slow_queries = []

In this way, you do not need to make any changes to your database and set up the demo directly. Meanwhile, we will add these options or utilize out-of-the-box tools like pgsty to ease the database changes.
