### ISSUE TITLE
tool_config.yaml

### ISSUE THREAD

**Issue by Polarisooo** [TsinghuaDatabaseGroup/DB-GPT#28]
What does the remote_directory in the tool_config.yaml refer to

**Comment by zhouxh19** [comment]
1. You need to rename tool_config_example.yaml into tool_config.yaml.
2. In tool_config.yaml, remote_directory indicates where the slow query log file is located at and you can configure it based on https://github.com/TsinghuaDatabaseGroup/DB-GPT#1-prerequisites.
