### ISSUE TITLE
How do you get the diagnosis knowledge?

### ISSUE THREAD

**Issue by Jun-jie-Huang** [TsinghuaDatabaseGroup/DB-GPT#37]
Dear authors,
I really appreciate your efforts in contributing to this wonderful repo. I have some questions about the acquisition of diagnosis knowledge. 

1. I see you have a file `diagnosis_code.txt` which contains codes to test different root cause. I'm wondering how do you obtain the code? Is it curated during your own DB maintanence experience or obtained from online resources? 
2. And also is it depend on specific software/DB that you want to diagnose, as some metric names can be different?
3. Do you have any suggestions for me to obtain such knowledge base? I'm thinking about apply your software to our service.

Thanks so much for your consideration!

**Comment by Jun-jie-Huang** [comment]
Thank you for your answers and suggestions. 

I agree that it is really hard to manually curate such knowledge. Some companies have their well-organized diagnosis knowledge base, but it is not open-sourced and also depends on their specific systems. 

I've also feelings during diagnosing systems and also hope to discuss with you.
A big problem I met is that we've already have many algorithms to detect anomalies, localize root causes, etc, to help failure diagnosis. But they are also designed for specific systems. I think LLM agents might be a solution to automatically resolve from failures. Use LLM to take a close look into the system behavior and perform reasoning like SREs. It is really like what SREs/DBAs do. 

Although I'm not sure how "realiable" the final mitigation suggestions provided by agents could be, I think the diagnosis can be automated. As using some functions to test the system and obtain system metrics does not intrustively affect the system. Before implementing the suggested mitigations, this period is secure. And also humans can check the mitigation suggestions before implementing. 

I think your work is really promising. I'm looking forward to your new release!

**Comment by zhouxh19** [comment]
> Thank you for your answers and suggestions.
> 
> I agree that it is really hard to manually curate such knowledge. Some companies have their well-organized diagnosis knowledge base, but it is not open-sourced and also depends on their specific systems.
> 
> I've also feelings during diagnosing systems and also hope to discuss with you. A big problem I met is that we've already have many algorithms to detect anomalies, localize root causes, etc, to help failure diagnosis. But they are also designed for specific systems. I think LLM agents might be a solution to automatically resolve from failures. Use LLM to take a close look into the system behavior and perform reasoning like SREs. It is really like what SREs/DBAs do.
> 
> Although I'm not sure how "realiable" the final mitigation suggestions provided by agents could be, I think the diagnosis can be automated. As using some functions to test the system and obtain system metrics does not intrustively affect the system. Before implementing the suggested mitigations, this period is secure. And also humans can check the mitigation suggestions before implementing.
> 
> I think your work is really promising. I'm looking forward to your new release!

a basic doc2knowledge is available at https://github.com/TsinghuaDatabaseGroup/DB-GPT/tree/new_ui/doc2knowledge
