### ISSUE TITLE
About the experience detection

### ISSUE THREAD

**Issue by Statisticss** [TsinghuaDatabaseGroup/DB-GPT#40]
Thank you for this great work! 
I have a question about the Sec. 4 in "LLM as DBA" paper. It says the experience format is ["name", "content", "metrics", "steps"], and is extracted from a document. However, in the repo I didn't see the code for this part. Instead, I found "knowledge_from_code" which extrat knowledge from diagnose codes, and in the format of ["cause_name", "desc", "metrics"]. Am I missing something here?

**Comment by zhouxh19** [comment]
you are right. 
The knowledge is from both code and document. For documents, they are from a commercial database vendor and it is not that easy to release them. Instead, we will first release the document extraction scripts soon.

**Comment by zhouxh19** [comment]
> Got it! Thank you. Looking forward to your document extraction scripts :)

a basic doc2knwoledge is available at https://github.com/TsinghuaDatabaseGroup/DB-GPT/tree/new_ui/doc2knowledge
