### ISSUE TITLE
vue页面显示为空

### ISSUE THREAD

**Issue by fdl1997** [TsinghuaDatabaseGroup/DB-GPT#53]
![img_v3_025c_6d6dea18-e674-4ccb-8924-d12fb3fd2ceg](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/90884015/1a6a2a7f-5c44-46ba-9fac-6bd5f0625607)
![img_v3_025c_eee52a84-bf4b-4766-b54e-86904a52443g](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/90884015/54a2e738-f70e-47a0-90ea-4269daa98d1a)
前端页面没有内容，会有一个空的报错框弹出，但终端看不到报错，是什么原因呢？

**Comment by HungryFour** [comment]
后端服务有启动吗？ 这个路径下面 ``` web_service/backend/run.sh ```

**Comment by fdl1997** [comment]
> > 这里服务有启动吗？ 这个路径下面`web_service/backend/run.sh`
> 
> 我是通过web_service/run_service.sh启动的这里面会把front和backend都启动吧

![img_v3_025c_df9acafd-8517-4d5e-882c-d52c21838deg](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/90884015/4741b858-c960-4f95-9145-85b4a7482f3e)
我查看了一下 app.py 是在运行着的

**Comment by HungryFour** [comment]
可以在前端页面右击=>检查=>Network，  看一下请求的报错

**Comment by fdl1997** [comment]
> 可以在前端页面右击=>检查=>网络，看一下请求的报错

![img_v3_025c_b5bc7234-4142-4739-be06-9f39a6566ccg](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/90884015/f1ec1f9d-9d66-475d-8c6d-5cad2dad95ae)

**Comment by ljn-aaa** [comment]
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/58469873/429f35f3-418c-4c92-9cd6-47fdbb1efbc7)

看了一下network的报错，请求的是后端的8024/histories..
测试了一下8024/test
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/58469873/15ad5d3f-03e7-4c83-8dc1-dfdd8568f5c5)
是能访问的

**Comment by ljn-aaa** [comment]
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/58469873/bd5086ae-ef92-4047-9b59-7012304c2856)
解决了，这里url有问题。 感谢。

**Comment by HungryFour** [comment]
是在服务器上启动的项目吗？ 改一下这个地方的请求地址，可以改成test接口的IP
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/8122332/b46c082b-484e-4bf0-84b6-9c91de04a097)

**Comment by HungryFour** [comment]
OK，后续我们会在文档里进行补充，感谢关注。
