### ISSUE TITLE
how to add new db-specified rules for the query rewrite tool?

### ISSUE THREAD

**Issue by louishust** [TsinghuaDatabaseGroup/DB-GPT#54]
hi, 

I saw the query rewrite use the LearnedRewrite.jar to do the rewrite job.
In the readme, LearnedRewrite.jar is derived from calcite,
may i know where is the repo of LearnedRewrite.jar?
If i want to add some new rules, how can i add the some db-specified rules?

**Comment by HungryFour** [comment]
You can find more information [here](https://github.com/evolveDB/LearnedRewrite.git)

**Comment by louishust** [comment]
@HungryFour thanks
