### ISSUE TITLE
Support for loading in lower precision

### ISSUE THREAD

**Issue by JINO-ROHIT** [TsinghuaDatabaseGroup/DB-GPT#62]
i have a small gpu, can i load the 13b llama in 4bit? Is there support for this?

**Comment by zhouxh19** [comment]
we will respond to this question after well testing in 4bit.

**Comment by JINO-ROHIT** [comment]
sure thank you

**Comment by curtis-sun** [comment]
We have provided a 4bit version (https://huggingface.co/curtis-sun/diag-baichuan2-4bit/tree/main) fine-tuned from Baichuan2-13B. Later we'll also upload more fine-tuned models.
