### ISSUE TITLE
/bin/sh: 1: mvn: not found

### ISSUE THREAD

**Issue by yangyongguang** [TsinghuaDatabaseGroup/DB-GPT#66]
import sys; print('Python %s on %s' % (sys.version, sys.platform))
/home/hw/miniconda3/envs/D-Bot/bin/python /home/hw/.pycharm_helpers/pydev/pydevd.py --multiprocess --qt-support=auto --client localhost --port 39485 --file /home/hw/YYG/D-Bot/DB-GPT/main.py 
Connected to pydev debugger (build 232.8660.197)

/bin/sh: 1: mvn: not found, 这里 readme 里面是不是缺 maven 的安装信息

**Comment by HungryFour** [comment]
这个是重写那边jar包的报错？重写那边的jar没有使用maven。

**Comment by yangyongguang** [comment]
您的邮件我已经收到了  我会及时的阅读 谢谢

**Comment by yangyongguang** [comment]
> mvn:
class java_rewrite(object):
    def __init__(self):
        self.start_jvm()
        pass

    def start_jvm(self):
        try:
            # 如果已经启动jvm的虚拟环境则跳过；否则进入else，启动java的虚拟环境
            if jpype.isJVMStarted():
                return True
            else:
                base_dir = os.path.abspath(os.curdir)
                local_lib_dir = os.path.join(base_dir+'/multiagents/tools/query_advisor/query_rewrite/', 'java_jar')
                _ = os.popen(
                    'mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt').read()
                classpath = open(
                    os.path.join(
                        base_dir,
                        'classpath.txt'),
                    'r').readline().split(':')
                classpath.extend([os.path.join(local_lib_dir, jar)
                                  for jar in os.listdir(local_lib_dir)])
                jp.startJVM(jp.getDefaultJVMPath(), classpath=classpath)
                print("系统启动java的jvm虚拟环境成功")
                return True
        except Exception as e:
            print("系统启动java的jvm虚拟环境出现错误,错误原因:" + str(e))
            return False



--------------------------------------------------------------------------------------------------------
_ = os.popen(
                    'mvn dependency:build-classpath -Dmdep.outputFile=classpath.txt').read()


这个函数使用了 mvn

**Comment by HungryFour** [comment]
您机器上的java是哪个版本？

**Comment by yangyongguang** [comment]
抱歉回复晚了

hw@Gundam:~$ java -version
openjdk version "11.0.21" 2023-10-17
OpenJDK Runtime Environment (build 11.0.21+9-post-Ubuntu-0ubuntu120.04)
OpenJDK 64-Bit Server VM (build 11.0.21+9-post-Ubuntu-0ubuntu120.04, mixed mode, sharing)

**Comment by HungryFour** [comment]
openjdk 版本有点低  别的好像也没啥  可以试试17版本以上的jdk。不过重写这个不用的话，也不影响跑通流程。

**Comment by yangyongguang** [comment]
您的邮件我已经收到了  我会及时的阅读 谢谢
