### ISSUE TITLE
running batch_main.py error

### ISSUE THREAD

**Issue by yangyongguang** [TsinghuaDatabaseGroup/DB-GPT#68]
process_num = 4
output_answer_file = "batch_testing_answers.jsonl"
result_log_prefix = "./alert_results/logs/diagnosis_results/"
log_dir_name = result_log_prefix + "2023-11-09-12-10-11"
reports_log_dir_name = log_dir_name + "/reports"

this var above, us not find in local project

**Comment by zhouxh19** [comment]
Thank you for your feedback. We have updated the batch_main.py script and fixed the problem

https://github.com/TsinghuaDatabaseGroup/DB-GPT/commit/9b3ed81b02c0da8dd61eb57fdf4c137a3cb445ef
