### ISSUE TITLE
得到了一个空的前端页面信息

### ISSUE THREAD

**Issue by yangyongguang** [TsinghuaDatabaseGroup/DB-GPT#70]
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/30389836/e866685b-bfa2-49e0-8245-eb06ecae7855)

![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/30389836/bd10ca6f-4ab4-4c1b-96d1-d195c69d1df5)

这里跑完了一个例子后页面依然是空的

**Comment by HungryFour** [comment]
这个地方有点问题。可能需要您手动把结果放到Llama2-13b的文件夹下面。 
![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/8122332/91cf6f0f-8d2d-4d17-98b2-97e429e574a2)
类似这样的。

**Comment by zhouxh19** [comment]
目录问题已解决：在./multiagents/agent_conf/config.yaml配置文件中指定存放报告的目录名。如：llm_type: GPT4-0613
