### ISSUE TITLE
running with baichung2 asks for openai error

### ISSUE THREAD

**Issue by JINO-ROHIT** [TsinghuaDatabaseGroup/DB-GPT#73]
![IMG_1795](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/63234112/17bd121c-9453-48b2-bef2-e0cba5f7b22a)

im using the baichung version of the project, but it throws an openai api key error

**Comment by curtis-sun** [comment]
You need to make sure that you set multiagents/agent_conf/config.yaml correctly, e.g., using diag-baichuan2(-4bit) like multiagents/agent_conf/config_diag_baichuan2.yaml.

**Comment by JINO-ROHIT** [comment]
![IMG_1796](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/63234112/da630e26-f6de-4c18-be47-df26e41f1ebd)
It says baichung is not registered

**Comment by curtis-sun** [comment]
I think you may register diag-baichuan2 in multiagents/llms/__init__.py

**Comment by JINO-ROHIT** [comment]
Can you show me how to do it? For baichung 4 bit

**Comment by curtis-sun** [comment]
add from .diag_baichuan2_4bit import DiagBaichuan2_4bitChat to __init__.py

**Comment by JINO-ROHIT** [comment]
Thanks, that worked, is there any token to this repo?
![IMG_1796](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/63234112/0195de6f-6dab-41cc-8c59-1c40a358c1c7)

**Comment by JINO-ROHIT** [comment]
Thanks
Is there any token to this repo?
![IMG_1797](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/63234112/ea0c6626-3b10-41b5-bb60-a125ef7bb491)

**Comment by curtis-sun** [comment]
The model is on https://huggingface.co/curtis-sun/diag-baichuan2-4bit/tree/main, maybe you should set load="curtis-sun/diag-baichuan2-4bit".

**Comment by JINO-ROHIT** [comment]
Thanks i managed to run it setting to my local path

**Comment by JINO-ROHIT** [comment]
![IMG_1798](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/63234112/2eb72587-653e-4b85-aae9-ce068351c1ea)
Im running the main.py file, it says analyzing with tools, but on the ui i dont see any new reports, what should be done next?

**Comment by zhouxh19** [comment]
You need to wait until new reports are generated within the ./alert_results directory (e.g., ./alert_results/Baichuan-13B/697303655.jsonl). Then, the information of the report will be demonstrated in the ui.

**Comment by JINO-ROHIT** [comment]
Ohh makes sense, thanks very much, closing the issue

**Comment by JINO-ROHIT** [comment]
Resolved
