### ISSUE TITLE
 readme里写的是pg12或更高版本，但pg15  pg_stat_statements表里没有total_time ; 改成total_exec_time了吧？

### ISSUE THREAD

**Issue by tzyodear** [TsinghuaDatabaseGroup/DB-GPT#80]
https://github.com/TsinghuaDatabaseGroup/DB-GPT/blob/34df9b6d9699851eecf2e6df8b98d792717c2039/utils/database.py#L335C28-L335C28

![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/44432612/287619f1-9710-42ae-a1ec-59d89ea5b9c0)

![image](https://github.com/TsinghuaDatabaseGroup/DB-GPT/assets/44432612/b2039239-68c9-4430-ab73-b6e2a5409c0a)

**Comment by HungryFour** [comment]
感谢，是有这个问题，我们先修改一下Readme。后期看看是不是能升级一下测试数据库
