### ISSUE TITLE
Clarification on UCT(v) Implementation in Tree Search Algorithm

### ISSUE THREAD

**Issue by andyyosshi** [TsinghuaDatabaseGroup/DB-GPT#98]
I found the concept of utilizing the UCT score intriguing. Specifically, I am curious about how the UCT(v) function is implemented in the actual code base.

In the paper, you describe the function as UCT(v) = w(v)/n(v) + C・√ln(N)/n(v), and I am trying to locate the exact part of the code that reflects this formula. Could you confirm if the logic around line 326 in `/multiagents/reasoning_algorithms/tree_of_thought/UCT_vote_function.py` is where this UCT computation takes place?

If not, could you please guide me to the right section in the code? Understanding the practical application of UCT(v) will greatly assist me in comprehending the overall tree search strategy you have proposed.

Thank you for your time and assistance.

**Comment by zhouxh19** [comment]
yes, but current logic is somewhat strange. We are developing a new version where each module is better decoupled, where it will be easier to modify the searching algorithm. Stay tuned for updates :-)
